# Generated by Django 5.1.2 on 2024-10-20 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome do usuário')),
                ('email', models.CharField(max_length=40, verbose_name='E-mail do usuário')),
                ('senha', models.CharField(max_length=40, unique=True, verbose_name='Senha do usuário')),
                ('idade', models.IntegerField(verbose_name='Idade do usuário')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(verbose_name='Nota do usuário')),
                ('comentario', models.CharField(max_length=500, verbose_name='Comentário do usuário')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Nome do Usuário')),
            ],
            options={
                'verbose_name': 'Forum',
                'verbose_name_plural': 'Fóruns',
            },
        ),
    ]
