# Generated by Django 5.1.1 on 2024-09-23 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome do admin')),
                ('email', models.CharField(max_length=40, verbose_name='E-mail do admin')),
                ('senha', models.CharField(max_length=40, unique=True, verbose_name='Senha do admin')),
                ('idade', models.IntegerField(verbose_name='Idade do admin')),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome do usuário')),
                ('email', models.CharField(max_length=40, verbose_name='E-mail do usuário')),
                ('senha', models.CharField(max_length=40, unique=True, verbose_name='Senha do usuário')),
                ('idade', models.IntegerField(verbose_name='Idade do usuário')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Placar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exibicao', models.CharField(max_length=3, verbose_name='Nome de exibição do usuário')),
                ('pontuacao', models.IntegerField(verbose_name='Pontuação do usuário')),
                ('data_de_jogada', models.DateField(verbose_name='Data da Pontuação do usuário')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário que marcou o ponto')),
            ],
            options={
                'verbose_name': 'Placar',
                'verbose_name_plural': 'Placar',
            },
        ),
    ]
