# Generated by Django 5.1.2 on 2024-10-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do usuário')),
                ('comentario', models.TextField(verbose_name='Comentário do usuário')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('jogo', models.TextField(verbose_name='Nome do jogo')),
            ],
        ),
    ]
