# Generated by Django 5.1.2 on 2024-10-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'Forum', 'verbose_name_plural': 'Fóruns'},
        ),
        migrations.AlterField(
            model_name='comentario',
            name='jogo',
            field=models.TextField(max_length=30, verbose_name='Nome do jogo'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do exibição'),
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
    ]
