# Generated by Django 5.1.2 on 2024-10-21 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_comentario_options_alter_comentario_jogo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comentario',
            new_name='texto',
        ),
    ]
