# Generated by Django 5.1.2 on 2024-10-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_comentario_comentario_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=40, unique=True, verbose_name='E-mail do usuário'),
        ),
    ]
