# Generated by Django 5.1.2 on 2024-10-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=40, verbose_name='Senha do usuário'),
        ),
    ]
