# Generated by Django 5.1.2 on 2024-10-21 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_usuario_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_logado',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Login'),
        ),
    ]
